window.LEVEL_DATA = {
level:"C2", color:"#0f766e",
title:"Deutsch C2 – Die Beherrschung",
subtitle:"Stil, Idiomatik und der Blick hinter die Grammatik.",
subtitleEn:"Style, idiom and the linguistics behind the grammar.",
topics:[

{id:"stilebenen", chip:"Stilebenen", title:"Stilebenen & Register", titleEn:"Registers — choosing the right level of language",
explain:"<p>Auf C2 entscheidest du bewusst, <b>wie</b> du etwas sagst. Dasselbe Anliegen, fünf Register:</p><table class='wide'><tr><th>Register<span class='en'>register</span></th><th>Beispiel: „Ich habe keine Zeit.“<span class='en'>example: “I have no time.”</span></th></tr><tr><td><b>salopp / umgangssprachlich</b></td><td>Keine Zeit, sorry. · Ich hab null Zeit.</td></tr><tr><td><b>neutral</b></td><td>Ich habe leider keine Zeit.</td></tr><tr><td><b>gehoben</b></td><td>Es fehlt mir derzeit an Zeit.</td></tr><tr><td><b>formell / behördlich</b></td><td>Aus terminlichen Gründen ist mir eine Teilnahme nicht möglich.</td></tr><tr><td><b>fachsprachlich</b></td><td>Die zeitlichen Ressourcen stehen aktuell nicht zur Verfügung.</td></tr></table><p><b>Woran erkennt man das Register?</b></p><ul><li><b>Wortwahl:</b> kriegen (salopp) – bekommen (neutral) – erhalten (gehoben)</li><li><b>Satzbau:</b> kurz und parataktisch (salopp) vs. lang und hypotaktisch (formell)</li><li><b>Nominalstil:</b> je formeller, desto mehr Nomen statt Verben</li><li><b>Passiv &amp; Unpersönlichkeit:</b> formelle Texte vermeiden „ich“</li></ul><p><b>Der C2-Fehler:</b> Register mischen — <i>„Sehr geehrte Damen und Herren, ich wollte mal fragen, ob ihr …“</i> Das wirkt unprofessionell.</p><p class='en'>C2 means choosing the register consciously and keeping it consistent. Mixing registers is the classic C2 mistake.</p>",
merk:"Ein Text, ein Register — niemals mischen.",
merkEn:"One text, one register — never mix.",
q:[
{q:"Welches Wort ist gehoben?", o:["kriegen","bekommen","erhalten"], c:2, h:"erhalten gehört in formelle Texte."},
{q:"Welcher Satz passt in ein Behördenschreiben?", o:["Ich kann leider nicht kommen.","Eine Teilnahme ist mir leider nicht möglich.","Klappt bei mir nicht."], c:1, h:"Nominal, unpersönlich, formell."},
{q:"Was kennzeichnet formelle Sprache?", o:["viele Verben, kurze Sätze","viele Nomen, Passiv, lange Sätze","viele Fragen"], c:1, h:"Nominalstil und Unpersönlichkeit."},
{type:"match", q:"Ordne Ausdruck und Register zu:", pairs:[["Ich hab keinen Bock.","salopp"],["Ich möchte nicht.","neutral"],["Ich bin nicht gewillt.","gehoben"],["Eine Bereitschaft besteht nicht.","behördlich"]], h:"Vom saloppen zum behördlichen Register."},
{type:"gap", q:"Gehobenes Synonym für „anfangen“: ___", a:["beginnen"], h:"anfangen (neutral) → beginnen (gehoben)."}
]},

{id:"idiomatik", chip:"Idiomatik", title:"Idiomatik: feste Wendungen & Redewendungen", titleEn:"Idioms and fixed expressions",
explain:"<p>Idiome versteht man nicht Wort für Wort. Wer sie richtig einsetzt, klingt wie ein Muttersprachler — wer sie falsch einsetzt, fällt auf.</p><table class='wide'><tr><th>Redewendung<span class='en'>idiom</span></th><th>Bedeutung<span class='en'>meaning</span></th></tr><tr><td><b>die Daumen drücken</b></td><td>jemandem Glück wünschen</td></tr><tr><td><b>ins Wasser fallen</b></td><td>abgesagt werden, nicht stattfinden</td></tr><tr><td><b>etwas auf die lange Bank schieben</b></td><td>aufschieben, verzögern</td></tr><tr><td><b>mit dem Kopf durch die Wand wollen</b></td><td>etwas erzwingen wollen</td></tr><tr><td><b>jemandem reinen Wein einschenken</b></td><td>die unangenehme Wahrheit sagen</td></tr><tr><td><b>Öl ins Feuer gießen</b></td><td>einen Streit verschärfen</td></tr><tr><td><b>aus dem Ruder laufen</b></td><td>außer Kontrolle geraten</td></tr><tr><td><b>Hand und Fuß haben</b></td><td>gut durchdacht sein</td></tr></table><p><b>Kollokationen</b> — Wörter, die fest zusammengehören. Hier verrät ein falsches Verb sofort den Lerner:</p><div class='ex'>eine Entscheidung <b>treffen</b> (nicht: machen) · eine Frage <b>stellen</b> (nicht: fragen) · Maßnahmen <b>ergreifen</b> · Kritik <b>üben</b> · einen Beitrag <b>leisten</b> · Verantwortung <b>übernehmen</b></div><p class='en'>Idioms cannot be translated word by word. Collocations are even more important: the wrong verb immediately marks you as a learner.</p>",
merk:"Nicht das Wort lernen, sondern die Kombination: eine Entscheidung TREFFEN.",
merkEn:"Learn the combination, not the single word.",
q:[
{q:"„Das Projekt ist ins Wasser gefallen.“ bedeutet:", o:["Es wurde nass.","Es fand nicht statt.","Es war erfolgreich."], c:1, h:"ins Wasser fallen = nicht stattfinden."},
{q:"Welches Verb passt? „eine Entscheidung ___“", o:["machen","treffen","nehmen"], c:1, h:"Kollokation: eine Entscheidung treffen."},
{q:"„jemandem reinen Wein einschenken“ heißt:", o:["großzügig sein","die Wahrheit sagen","jemanden einladen"], c:1, h:"Unangenehme Wahrheit offen sagen."},
{type:"match", q:"Ordne Redewendung und Bedeutung zu:", pairs:[["die Daumen drücken","Glück wünschen"],["auf die lange Bank schieben","aufschieben"],["Öl ins Feuer gießen","Streit verschärfen"],["Hand und Fuß haben","gut durchdacht sein"]], h:"Vier häufige Redewendungen."},
{type:"gap", q:"Kollokation: Maßnahmen ___ <span class='en'>(take measures)</span>", a:["ergreifen"], h:"Maßnahmen ergreifen."}
]},

{id:"textsorten", chip:"Textsorten", title:"Textsorten & ihre Muster", titleEn:"Text types and their conventions",
explain:"<p>Jede Textsorte hat feste Erwartungen. Wer sie kennt, schreibt schneller und überzeugender.</p><table class='wide'><tr><th>Textsorte<span class='en'>text type</span></th><th>Merkmale<span class='en'>features</span></th><th>Typische Sprache<span class='en'>typical language</span></th></tr><tr><td><b>Erörterung</b></td><td>These → Argumente pro/contra → Fazit</td><td>Einerseits …, andererseits …; Abschließend lässt sich festhalten</td></tr><tr><td><b>Bericht</b></td><td>sachlich, chronologisch, W-Fragen</td><td>Präteritum, Passiv, keine Wertung</td></tr><tr><td><b>Stellungnahme</b></td><td>Position + Begründung + Beispiel</td><td>Ich vertrete die Auffassung …; Dem ist entgegenzuhalten …</td></tr><tr><td><b>Zusammenfassung</b></td><td>nur Kerninhalte, eigene Worte</td><td>Präsens, indirekte Rede: Der Autor führt aus, dass …</td></tr><tr><td><b>Geschäftsbrief</b></td><td>Betreff, Anrede, Anliegen, Frist, Gruß</td><td>Sehr geehrte …; Ich beziehe mich auf …; Mit freundlichen Grüßen</td></tr><tr><td><b>Protokoll</b></td><td>Ort, Zeit, Teilnehmer, Beschlüsse</td><td>Nominalstil, Passiv, Präsens</td></tr></table><p><b>Die drei Fragen vor jedem Text:</b> Wer liest das? Was soll danach passieren? Welches Register ist angemessen?</p><p class='en'>Every text type has fixed conventions. Before writing, ask: who reads this, what should happen next, which register fits?</p>",
merk:"Erst Leser und Ziel klären, dann schreiben — nie umgekehrt.",
merkEn:"Clarify reader and purpose first, then write.",
q:[
{q:"Welche Zeit benutzt eine Zusammenfassung?", o:["Präteritum","Präsens","Futur"], c:1, h:"Zusammenfassungen stehen im Präsens."},
{q:"Was gehört NICHT in einen Bericht?", o:["Datum und Ort","persönliche Wertung","chronologischer Ablauf"], c:1, h:"Berichte sind sachlich und wertfrei."},
{q:"„Dem ist entgegenzuhalten, dass …“ passt in:", o:["ein Protokoll","eine Stellungnahme","eine Einladung"], c:1, h:"Gegenargument in der Stellungnahme."},
{type:"match", q:"Ordne Textsorte und Merkmal zu:", pairs:[["Erörterung","pro und contra"],["Bericht","sachlich, chronologisch"],["Protokoll","Beschlüsse festhalten"],["Zusammenfassung","Kerninhalte in eigenen Worten"]], h:"Vier Textsorten mit klaren Mustern."}
]},

{id:"rhetorik", chip:"Rhetorik", title:"Rhetorische Mittel", titleEn:"Rhetorical devices",
explain:"<p>Rhetorische Mittel erkennst du in Reden, Werbung und Literatur — und setzt sie selbst gezielt ein.</p><table class='wide'><tr><th>Mittel<span class='en'>device</span></th><th>Was passiert<span class='en'>what happens</span></th><th>Beispiel<span class='en'>example</span></th></tr><tr><td><b>Metapher</b></td><td>Bild statt Sachwort</td><td>Das Herz der Stadt</td></tr><tr><td><b>Vergleich</b></td><td>mit wie / als</td><td>stark wie ein Löwe</td></tr><tr><td><b>Rhetorische Frage</b></td><td>Frage ohne Antworterwartung</td><td>Wer will das schon?</td></tr><tr><td><b>Anapher</b></td><td>Wiederholung am Satzanfang</td><td>Wir brauchen Mut. Wir brauchen Zeit.</td></tr><tr><td><b>Klimax</b></td><td>Steigerung</td><td>Er kam, sah und siegte.</td></tr><tr><td><b>Ironie</b></td><td>Gegenteil des Gemeinten</td><td>Toll gemacht! <span class='small'>(nach einem Fehler)</span></td></tr><tr><td><b>Euphemismus</b></td><td>Beschönigung</td><td>Freisetzung <span class='small'>(statt Entlassung)</span></td></tr><tr><td><b>Untertreibung</b></td><td>bewusst abschwächen</td><td>nicht schlecht <span class='small'>(= sehr gut)</span></td></tr></table><p><b>Für die Prüfung wichtig:</b> Erkennen, <b>warum</b> ein Autor ein Mittel einsetzt — meist um zu überzeugen, zu verharmlosen oder Emotionen zu wecken.</p><p class='en'>Recognize these devices in speeches, advertising and literature — and understand why the author uses them.</p>",
merk:"Frag immer: Was will der Autor damit erreichen?",
merkEn:"Always ask: what effect is the author after?",
q:[
{q:"„Freisetzung“ statt „Entlassung“ ist ein:", o:["Euphemismus","Metapher","Vergleich"], c:0, h:"Beschönigung = Euphemismus."},
{q:"„Wir kämpfen. Wir hoffen. Wir gewinnen.“ — welches Mittel?", o:["Ironie","Anapher","Euphemismus"], c:1, h:"Wiederholung am Satzanfang."},
{q:"„Das ist ja nicht schlecht“ nach einer perfekten Leistung ist:", o:["Untertreibung","Klimax","Metapher"], c:0, h:"Bewusste Abschwächung."},
{type:"match", q:"Ordne zu:", pairs:[["Metapher","Bild statt Sachwort"],["Anapher","Wiederholung am Anfang"],["Klimax","Steigerung"],["Ironie","Gegenteil gemeint"]], h:"Vier Grundmittel der Rhetorik."}
]},

{id:"varietaeten", chip:"Varietäten", title:"Varietäten: Dialekt, Umgangssprache, Fachsprache", titleEn:"Varieties of German",
explain:"<p>„Das Deutsche“ gibt es nicht — es gibt viele Varietäten:</p><table class='wide'><tr><th>Varietät<span class='en'>variety</span></th><th>Merkmale<span class='en'>features</span></th><th>Beispiel<span class='en'>example</span></th></tr><tr><td><b>Standarddeutsch</b></td><td>überregional, Norm der Schriftsprache</td><td>Ich habe gearbeitet.</td></tr><tr><td><b>Umgangssprache</b></td><td>mündlich, verkürzt, regional gefärbt</td><td>Ich hab gearbeitet. · Haste mal Zeit?</td></tr><tr><td><b>Dialekt</b></td><td>stark regional, eigene Grammatik</td><td>I hob gschafft. <span class='small'>(bairisch)</span></td></tr><tr><td><b>Fachsprache</b></td><td>präzise, viele Fachbegriffe, Nominalstil</td><td>Die Applikation der Substanz erfolgt intravenös.</td></tr><tr><td><b>Jugendsprache</b></td><td>schnelllebig, kreativ, Anglizismen</td><td>Das ist echt random.</td></tr></table><p><b>Nationale Varianten:</b> Deutsch ist plurizentrisch — Deutschland, Österreich und die Schweiz haben eigene Standardformen:</p><div class='ex'>D: Tüte · A: Sackerl · CH: Säckli<br>D: Januar · A/CH: Jänner<br>D: das Tram · CH: <b>die</b> Tram · CH schreibt kein <b>ß</b>, sondern immer <b>ss</b></div><p><b>Für Lernende wichtig:</b> Lerne Standarddeutsch aktiv, verstehe Umgangssprache passiv. Dialekt musst du nicht sprechen können.</p><p class='en'>German is pluricentric: Germany, Austria and Switzerland have their own standard forms. Learn the standard actively, understand colloquial speech passively.</p>",
merk:"Aktiv Standard, passiv Umgangssprache — Dialekt nur verstehen, nicht sprechen.",
merkEn:"Actively standard, passively colloquial. Dialect: understand only.",
q:[
{q:"Welche Form ist Standarddeutsch?", o:["Ich hab kein Bock.","Ich habe keine Lust.","I mog ned."], c:1, h:"Vollform, neutrale Wortwahl."},
{q:"In der Schweiz schreibt man statt „ß“:", o:["sz","ss","s"], c:1, h:"Die Schweiz kennt kein ß."},
{q:"Was ist ein Austriazismus?", o:["Tüte","Jänner","Januar"], c:1, h:"Jänner = österreichisches Standarddeutsch."},
{type:"match", q:"Ordne Varietät und Beispiel zu:", pairs:[["Standard","Ich habe gearbeitet."],["Umgangssprache","Ich hab gearbeitet."],["Dialekt","I hob gschafft."],["Fachsprache","Die Applikation erfolgt intravenös."]], h:"Vier Stufen derselben Sprache."}
]},

{id:"grundbegriffe", chip:"Fachbegriffe", title:"Linguistische Grundbegriffe", titleEn:"Core linguistic terminology",
explain:"<p>Diese Begriffe brauchst du, um über Grammatik zu <b>sprechen</b> — im Studium, im Unterricht, in jedem Lehrwerk.</p><table class='wide'><tr><th>Begriff<span class='en'>term</span></th><th>Bedeutung<span class='en'>meaning</span></th><th>Beispiel<span class='en'>example</span></th></tr><tr><td><b>Genus</b></td><td>grammatisches Geschlecht</td><td>der / die / das</td></tr><tr><td><b>Kasus</b></td><td>Fall</td><td>Nominativ, Akkusativ, Dativ, Genitiv</td></tr><tr><td><b>Numerus</b></td><td>Zahl</td><td>Singular / Plural</td></tr><tr><td><b>Tempus</b></td><td>Zeitform</td><td>Präsens, Perfekt, Futur</td></tr><tr><td><b>Modus</b></td><td>Aussageweise</td><td>Indikativ, Konjunktiv, Imperativ</td></tr><tr><td><b>Genus Verbi</b></td><td>Aktiv oder Passiv</td><td>er baut / es wird gebaut</td></tr><tr><td><b>Flexion</b></td><td>Formveränderung</td><td>Deklination (Nomen) + Konjugation (Verben)</td></tr><tr><td><b>Valenz</b></td><td>wie viele Ergänzungen ein Verb fordert</td><td>helfen + Dativ</td></tr><tr><td><b>Agens / Patiens</b></td><td>Täter / Betroffener</td><td>Der Hund (Agens) beißt den Mann (Patiens).</td></tr><tr><td><b>Morphem</b></td><td>kleinste bedeutungstragende Einheit</td><td>un-freund-lich = 3 Morpheme</td></tr></table><p><b>Die vier Ebenen der Sprachwissenschaft:</b> <b>Phonetik</b> (Laute) → <b>Morphologie</b> (Wortformen) → <b>Syntax</b> (Satzbau) → <b>Semantik</b> (Bedeutung) → <b>Pragmatik</b> (Gebrauch im Kontext).</p><p class='en'>These terms let you talk about grammar itself — essential for studying or teaching German.</p>",
merk:"Genus = Geschlecht, Numerus = Zahl, Kasus = Fall, Tempus = Zeit, Modus = Aussageweise.",
merkEn:"Genus, Numerus, Kasus, Tempus, Modus — the five basic categories.",
q:[
{q:"Was bezeichnet „Numerus“?", o:["den Fall","Singular oder Plural","die Zeitform"], c:1, h:"Numerus = Zahl."},
{q:"„Konjunktiv“ ist ein …", o:["Kasus","Modus","Tempus"], c:1, h:"Indikativ, Konjunktiv, Imperativ = Modi."},
{q:"Wie viele Morpheme hat „unfreundlich“?", o:["1","2","3"], c:2, h:"un + freund + lich."},
{q:"Welche Ebene untersucht den Satzbau?", o:["Morphologie","Syntax","Semantik"], c:1, h:"Syntax = Satzbau."},
{type:"match", q:"Ordne Begriff und Bedeutung zu:", pairs:[["Genus","grammatisches Geschlecht"],["Kasus","Fall"],["Tempus","Zeitform"],["Valenz","Ergänzungen des Verbs"],["Morphem","kleinste Bedeutungseinheit"]], h:"Die Grundbegriffe der Grammatikbeschreibung."}
]},

{id:"phonetik", chip:"Aussprache", title:"Phonetik: Laute, Silben & Betonung", titleEn:"Pronunciation: sounds, syllables, stress",
explain:"<p>Auf C2 geht es um die letzten Prozente — Aussprache verrät den Lerner länger als die Grammatik.</p><p><b>Die schwierigsten Laute für Lernende:</b></p><table class='wide'><tr><th>Laut<span class='en'>sound</span></th><th>Tipp<span class='en'>tip</span></th><th>Beispiele<span class='en'>examples</span></th></tr><tr><td><b>ü / ö</b></td><td>Lippen runden wie bei u/o, aber i/e sagen</td><td>über, müde, schön, hören</td></tr><tr><td><b>ch</b> (weich)</td><td>nach e, i, ä, ö, ü, l, r, n</td><td>ich, nicht, Milch, Bücher</td></tr><tr><td><b>ch</b> (hart)</td><td>nach a, o, u, au</td><td>ach, Buch, kochen, auch</td></tr><tr><td><b>r</b></td><td>im Rachen, am Wortende fast wie „a“</td><td>rot; aber: Vater ≈ „Vata“</td></tr><tr><td><b>z / tz</b></td><td>immer „ts“, nie wie englisches z</td><td>Zeit, jetzt, Platz</td></tr><tr><td><b>v / w</b></td><td>v = f, w = englisches v</td><td>Vater = „Fater“, Wasser</td></tr><tr><td><b>Auslautverhärtung</b></td><td>b, d, g am Wortende → p, t, k</td><td>Tag = „Tak“, Hund = „Hunt“</td></tr></table><p><b>Wortbetonung:</b> meist auf der ersten Silbe (<b>Ar</b>beit, <b>Lehr</b>er). Aber: trennbare Verben betonen die Vorsilbe (<b>ein</b>kaufen), untrennbare den Stamm (be<b>su</b>chen). Fremdwörter oft hinten (Stu<b>dent</b>, Universi<b>tät</b>).</p><p><b>Satzmelodie:</b> Aussage fällt am Ende ↓ · W-Frage fällt ↓ · Ja/Nein-Frage steigt ↑</p><p class='en'>Pronunciation reveals learners longer than grammar does. Watch ü/ö, the two ch sounds, final devoicing, and stress on separable prefixes.</p>",
merk:"„einkaufen“ betont vorn, „besuchen“ betont hinten — die Vorsilbe entscheidet.",
merkEn:"Separable prefix = stressed. Inseparable = stem is stressed.",
q:[
{q:"Wie spricht man „Tag“ am Wortende?", o:["Tag mit g","Tak","Tach"], c:1, h:"Auslautverhärtung: g → k."},
{q:"Welche Silbe wird betont? „einkaufen“", o:["ein","kau","fen"], c:0, h:"Trennbare Vorsilbe wird betont."},
{q:"Welche Silbe wird betont? „besuchen“", o:["be","su","chen"], c:1, h:"Untrennbare Vorsilbe unbetont, Stamm betont."},
{q:"Wie spricht man „Vater“?", o:["mit englischem v","wie f","wie w"], c:1, h:"v = f im Deutschen."},
{type:"match", q:"Ordne Wort und ch-Laut zu:", pairs:[["ich","weiches ch"],["Buch","hartes ch"],["Milch","weiches ch"],["kochen","hartes ch"]], h:"Nach a, o, u, au → hart. Sonst weich."}
]},

{id:"wortbildungc2", chip:"Wortbildung wissenschaftlich", title:"Wortbildung: Derivation, Komposition, Konversion", titleEn:"Word formation from a linguistic view",
explain:"<p>Deutsch bildet neue Wörter auf vier Wegen. Wer das System kennt, versteht auch Wörter, die es noch gar nicht gibt.</p><table class='wide'><tr><th>Verfahren<span class='en'>process</span></th><th>Was passiert<span class='en'>what happens</span></th><th>Beispiel<span class='en'>example</span></th></tr><tr><td><b>Komposition</b></td><td>zwei Wörter verbinden</td><td>Haus + Tür → Haustür</td></tr><tr><td><b>Derivation</b></td><td>Vor- oder Nachsilbe anhängen</td><td>Freund → Freund<b>schaft</b> · <b>un</b>freundlich</td></tr><tr><td><b>Konversion</b></td><td>Wortart wechseln ohne Anhang</td><td>essen → das Essen · gut → das Gute</td></tr><tr><td><b>Kurzwortbildung</b></td><td>abkürzen</td><td>Universität → Uni · Lastkraftwagen → Lkw</td></tr></table><p><b>Produktivität:</b> Manche Muster sind lebendig und erzeugen ständig neue Wörter (<i>-bar</i>, <i>-ung</i>, Komposition), andere sind erstarrt (<i>-nis</i>, <i>-t</i> wie in Fahrt).</p><p><b>Kopf-Prinzip:</b> Bei Komposita bestimmt das <b>rechte</b> Element Wortart, Genus und Grundbedeutung — deshalb ist <i>der Kühlschrank</i> ein Schrank, kein Kühlen.</p><p><b>Semantische Fallen:</b> Nicht jedes Kompositum ist durchsichtig. <i>Handschuh</i> = Schuh für die Hand ✓, aber <i>Junggeselle</i> ist kein junger Geselle mehr — die Bedeutung hat sich verselbstständigt (Lexikalisierung).</p><p class='en'>Four processes: compounding, derivation, conversion, abbreviation. The right-hand element is the head. Some compounds have lexicalized and lost their transparent meaning.</p>",
merk:"Rechts steht der Kopf: Kühlschrank ist ein Schrank.",
merkEn:"The right element is the head: Kühlschrank is a Schrank.",
q:[
{q:"„das Essen“ (aus dem Verb essen) entsteht durch:", o:["Komposition","Derivation","Konversion"], c:2, h:"Wortartwechsel ohne Anhang = Konversion."},
{q:"„Freundschaft“ entsteht durch:", o:["Derivation","Komposition","Kurzwort"], c:0, h:"Nachsilbe -schaft angehängt."},
{q:"Welches Element bestimmt Genus und Bedeutung eines Kompositums?", o:["das linke","das rechte","beide gleich"], c:1, h:"Kopf-Prinzip: rechts."},
{type:"match", q:"Ordne Verfahren und Beispiel zu:", pairs:[["Komposition","Haustür"],["Derivation","unfreundlich"],["Konversion","das Laufen"],["Kurzwort","Uni"]], h:"Vier Wege der Wortbildung."}
]},

{id:"sprachwandel", chip:"Sprachwandel", title:"Sprachwandel & Zweifelsfälle", titleEn:"Language change and disputed forms",
explain:"<p>Sprache verändert sich. Auf C2 solltest du wissen, wo die Norm schwankt — und dich bewusst entscheiden.</p><table class='wide'><tr><th>Zweifelsfall<span class='en'>disputed case</span></th><th>Standard<span class='en'>standard</span></th><th>Tendenz<span class='en'>tendency</span></th></tr><tr><td>Genitiv nach <i>wegen</i></td><td>wegen <b>des</b> Regens</td><td>gesprochen: wegen dem Regen</td></tr><tr><td>Perfekt von <i>stehen, liegen, sitzen</i></td><td>D: hat gestanden</td><td>Süd/A/CH: ist gestanden</td></tr><tr><td><i>weil</i> mit Hauptsatzstellung</td><td>weil ich müde <b>bin</b></td><td>gesprochen: weil ich bin müde</td></tr><tr><td>Konjunktiv II starker Verben</td><td>er käme, gäbe, träfe</td><td>ersetzt durch würde + Infinitiv</td></tr><tr><td>Anglizismen</td><td>herunterladen</td><td>downloaden, gedownloadet</td></tr><tr><td>Gendern</td><td>Lehrerinnen und Lehrer</td><td>Lehrende, Lehrer:innen — umstritten</td></tr></table><p><b>Deskriptiv oder präskriptiv?</b> Der Duden beschreibt zunehmend, was Menschen tatsächlich sagen, statt nur vorzuschreiben. Für Prüfungen gilt trotzdem: <b>schreibe die Standardnorm</b>, auch wenn du im Alltag anderes hörst.</p><p class='en'>Language changes; the standard wavers in places. In exams always write the standard form, even if you hear something else in daily life.</p>",
merk:"In der Prüfung immer die Standardnorm — im Gespräch darfst du hören, was üblich ist.",
merkEn:"Write the standard in exams; listen to what people actually say in daily life.",
q:[
{q:"Standardsprachlich korrekt ist:", o:["wegen dem Wetter","wegen des Wetters","wegen das Wetter"], c:1, h:"wegen + Genitiv ist die Norm."},
{q:"„Weil ich bin müde“ — was stimmt hier nicht?", o:["nichts","nach weil muss das Verb ans Ende","weil ist falsch"], c:1, h:"Standard: weil ich müde bin."},
{q:"Welche Konjunktiv-II-Form wird heute meist ersetzt?", o:["hätte","wäre","träfe"], c:2, h:"Starke Formen weichen würde + Infinitiv."},
{type:"gap", q:"Standardform: „Trotz ___ Regens gingen wir.“ (der Regen, Genitiv)", a:["des"], h:"trotz + Genitiv: des Regens."}
]},

{id:"redemittelc2", chip:"Redemittel", title:"Redemittel C2: souverän formulieren", titleEn:"C2 phrases — speaking with authority",
explain:"<div class='vgrid'><div class='vbox'><h4>Präzise positionieren</h4><ul><li>Ich neige zu der Auffassung, dass …<span class='en'>I tend to take the view</span></li><li>Dem würde ich insofern zustimmen, als …<span class='en'>I'd agree insofar as</span></li><li>Das trifft nur bedingt zu.<span class='en'>that's only partly true</span></li><li>Hier ist zu differenzieren zwischen …<span class='en'>one must differentiate</span></li></ul></div><div class='vbox'><h4>Elegant widersprechen</h4><ul><li>Bei aller Sympathie für dieses Argument …<span class='en'>with all sympathy for that argument</span></li><li>Das greift meines Erachtens zu kurz.<span class='en'>that falls short</span></li><li>Dem lässt sich entgegenhalten, dass …<span class='en'>one could counter that</span></li><li>Ich sehe das mit gewissen Vorbehalten.<span class='en'>I have certain reservations</span></li></ul></div><div class='vbox'><h4>Moderieren & strukturieren</h4><ul><li>Lassen Sie mich das kurz einordnen.<span class='en'>let me put this in context</span></li><li>Um auf Ihren Punkt zurückzukommen …<span class='en'>coming back to your point</span></li><li>Damit wären wir beim Kern der Sache.<span class='en'>that brings us to the heart of it</span></li><li>Ich fasse zusammen: …<span class='en'>to summarize</span></li></ul></div><div class='vbox'><h4>Abtönen & abschwächen</h4><ul><li>Es spricht einiges dafür, dass …<span class='en'>there's much to suggest</span></li><li>Man könnte durchaus argumentieren, dass …<span class='en'>one could well argue</span></li><li>Das mag zutreffen, allerdings …<span class='en'>that may be so, however</span></li><li>Vorsichtig formuliert: …<span class='en'>to put it cautiously</span></li></ul></div></div><p class='en'>C2 phrases: positioning yourself precisely, disagreeing elegantly, moderating a discussion and softening a statement without losing clarity.</p>",
merk:"C2 heißt nicht lauter, sondern genauer: „Das trifft nur bedingt zu.“",
merkEn:"C2 is not louder but more precise."}
]};
