/* FLOß – 27 Hauptthemen mit Unterthemen und je einem geprüften Erklärvideo */
window.MAIN_TOPICS = [
{id:"artikel-nomen", name:"Artikel & Nomen", en:"Articles & nouns", icon:"◆", color:"#22a04c",
 desc:"Jedes Nomen hat ein Geschlecht — der, die oder das. Dazu Sonderfälle wie der Nullartikel.",
 yt:"uxHhFXKyZjc", ytTitle:"Das Genus: der – die oder das?",
 subs:[["a1","artikel"],["a1","nullartikel"],["a1","deklination"],["a2","ndeklination"],["c2","grundbegriffe"]]},
{id:"plural", name:"Plural", en:"Plural forms", icon:"❊", color:"#22a04c",
 desc:"Fünf Muster für die Mehrzahl — und warum der Artikel im Plural immer „die“ ist.",
 yt:"4UUsuDkANAU", ytTitle:"Alle Pluralendungen erklärt",
 subs:[["a1","plural"]]},
{id:"faelle", name:"Die vier Fälle", en:"The four cases", icon:"⬢", color:"#0a6fe8",
 desc:"Nominativ, Akkusativ, Dativ, Genitiv — wer macht was mit wem.",
 yt:"llIfpKRKtgg", ytTitle:"Die 4 Fälle einfach erklärt",
 subs:[["a1","akkusativ"],["a2","dativ"],["b1","genitiv"],["a2","deklination2"],["b1","deklination3"],["b1","valenz"]]},
{id:"adjektive", name:"Adjektive", en:"Adjectives", icon:"✧", color:"#7c3aed",
 desc:"Endungen, Steigerung und Adjektive, die zu Nomen werden.",
 yt:"w-hI9IwmjUs", ytTitle:"Alles über die Adjektivdeklination",
 subs:[["b1","adjektiv"],["b1","adjektivnomen"],["b2","adjpraep"],["b1","attribute"]]},
{id:"steigerung", name:"Vergleich & Steigerung", en:"Comparison", icon:"⇗", color:"#7c3aed",
 desc:"größer als, so groß wie, am größten — Adjektive vergleichen.",
 yt:"mi_LAAuYRRc", ytTitle:"Komparativ & Superlativ einfach erklärt",
 subs:[["a2","komparativ"],["a2","gradpartikel"]]},
{id:"pronomen", name:"Pronomen", en:"Pronouns", icon:"↻", color:"#0891b2",
 desc:"Wörter, die für ein Nomen stehen — von „er“ über „dieser“ bis „worauf“.",
 yt:"Yp7xYBkN55s", ytTitle:"Personalpronomen und Possessivpronomen",
 subs:[["a1","personalpronomen"],["a1","possessiv"],["a2","indefinit"],["a2","demonstrativ"],["b1","pronominaladverb"],["b1","platzhalteres"]]},
{id:"praesens", name:"Präsens", en:"Present tense", icon:"▶", color:"#0a6fe8",
 desc:"Die Gegenwart und wie man Verben konjugiert — regelmäßig und unregelmäßig.",
 yt:"nJCll_AMRLo", ytTitle:"Konjugation im Präsens einfach erklärt",
 subs:[["a1","praesens"],["a1","verbtabellen"],["a1","haeufige-verben"]]},
{id:"vergangenheit", name:"Vergangenheit", en:"Past tenses", icon:"◀", color:"#0a6fe8",
 desc:"Perfekt zum Sprechen, Präteritum zum Schreiben, Plusquamperfekt für davor.",
 yt:"BVaDmkoNnDc", ytTitle:"Perfekt und Präteritum — über Vergangenes sprechen",
 subs:[["a2","perfekt"],["a2","praeteritum"],["a2","verbtabellen2"],["b1","plusquamperfekt"],["b1","verbtabellen3"]]},
{id:"zukunft", name:"Zukunft", en:"Future tenses", icon:"⇥", color:"#0a6fe8",
 desc:"Futur I und II — und warum Deutsche für Pläne meist das Präsens benutzen.",
 yt:"QsMzF_b4LI4", ytTitle:"Futur I — die Zeitform der Zukunft",
 subs:[["a2","futur1"],["b1","futur2"],["b2","tempuswechsel"]]},
{id:"modalverben", name:"Modalverben", en:"Modal verbs", icon:"⚑", color:"#dc2626",
 desc:"können, müssen, dürfen, wollen, sollen, mögen — und ihre versteckten Bedeutungen.",
 yt:"jryxTpOqymE", ytTitle:"Alle Modalverben einfach erklärt",
 subs:[["a1","modalverben"],["b2","submodal"]]},
{id:"trennbare", name:"Trennbare Verben", en:"Separable verbs", icon:"⇄", color:"#dc2626",
 desc:"Verben, die sich im Satz teilen — die Vorsilbe fliegt ans Ende.",
 yt:"B0uUDrhC690", ytTitle:"Trennbare und untrennbare Verben",
 subs:[["a1","trennbar"],["b2","wortbildungb2"]]},
{id:"reflexive", name:"Reflexive Verben", en:"Reflexive verbs", icon:"⟲", color:"#dc2626",
 desc:"Verben mit sich — echt reflexiv, teilreflexiv oder mit Dativ.",
 yt:"m_nPdA8l7K4", ytTitle:"Reflexive Verben — A2 bis B2",
 subs:[["a2","reflexiv"],["a2","reflexivarten"],["b1","reflexivb1"]]},
{id:"passiv", name:"Passiv", en:"Passive voice", icon:"⇤", color:"#dc2626",
 desc:"Wenn die Handlung wichtiger ist als der Täter — inklusive aller Ersatzformen.",
 yt:"89PRXLuGySQ", ytTitle:"Alles über das Passiv in 20 Minuten",
 subs:[["b1","passiv"],["b2","passiv2"],["b2","zustandspassiv"],["c1","passivc1"],["b2","gerundivum"]]},
{id:"konjunktiv2", name:"Konjunktiv II", en:"Subjunctive II", icon:"◇", color:"#9333ea",
 desc:"wäre, hätte, würde — höflich sein, Wünsche äußern, Irreales ausdrücken.",
 yt:"N5LzL46snao", ytTitle:"Konjunktiv II: hätte, wäre, würde",
 subs:[["b1","konj2"],["b2","konj2v"],["c1","irreal"],["b2","konjtabelle"]]},
{id:"konjunktiv1", name:"Indirekte Rede", en:"Reported speech", icon:"❝", color:"#9333ea",
 desc:"Konjunktiv I — wiedergeben, was andere gesagt haben, ohne es zu behaupten.",
 yt:"4xdlx1oZkI8", ytTitle:"Konjunktiv 1 — Verwendung und Bildung",
 subs:[["b2","konj1"],["c1","redewiedergabe"]]},
{id:"imperativ", name:"Imperativ", en:"Imperative", icon:"!", color:"#dc2626",
 desc:"Befehle, Bitten und Anweisungen — du, ihr und Sie.",
 yt:"U2ErysRF9eE", ytTitle:"Imperativ — die Befehlsform",
 subs:[["a2","imperativ"],["a1","hoeflichkeit"]]},
{id:"praepositionen", name:"Präpositionen", en:"Prepositions", icon:"⇢", color:"#0d9488",
 desc:"Welcher Fall folgt? Feste Präpositionen, Wechselpräpositionen und Verschmelzungen.",
 yt:"LdIQBJ_k2vo", ytTitle:"Alles über Wechselpräpositionen in 15 Minuten",
 subs:[["a2","wechsel"],["a1","verschmelzung"]]},
{id:"verbpraep", name:"Verben mit Präposition", en:"Verbs with prepositions", icon:"⚯", color:"#0d9488",
 desc:"warten auf, denken an, bestehen aus — Verb, Präposition und Fall als Einheit.",
 yt:"Yh96nluPR5M", ytTitle:"Verben mit Präpositionen endlich verstehen",
 subs:[["a2","verbpraep2"],["b1","verbpraep"],["b2","verbpraep3"],["c1","rektion"]]},
{id:"satzbau", name:"Satzbau & Wortstellung", en:"Word order", icon:"⟶", color:"#e07a08",
 desc:"Verb auf Position 2, Satzklammer, TEKAMOLO — das Rückgrat des deutschen Satzes.",
 yt:"k94Ioe_kvDY", ytTitle:"Der Satzbau-Guide: korrekte Sätze schreiben",
 subs:[["a1","satzbau"],["a2","satzglieder"],["a2","tekamolo"],["c1","feldermodell"],["c1","ellipse"]]},
{id:"fragen", name:"Fragen", en:"Questions", icon:"?", color:"#e07a08",
 desc:"W-Fragen, Ja/Nein-Fragen und höfliche indirekte Fragen.",
 yt:"Ntsq6cHp2Lk", ytTitle:"Ja-Nein-Fragen und W-Fragen einfach erklärt",
 subs:[["a1","fragen"],["a2","indirektefrage"]]},
{id:"negation", name:"Verneinung", en:"Negation", icon:"⊘", color:"#e07a08",
 desc:"nicht oder kein — und wo genau im Satz das „nicht“ steht.",
 yt:"ICx506KBMxk", ytTitle:"Deutsche Verneinung: nein, nicht oder kein?",
 subs:[["a1","negation"],["a2","nichtstellung"]]},
{id:"nebensaetze", name:"Nebensätze", en:"Subordinate clauses", icon:"⤷", color:"#9333ea",
 desc:"weil, dass, wenn, obwohl — und alle Satztypen von temporal bis konzessiv.",
 yt:"h1LXkj1Ug00", ytTitle:"weil, dass, wenn, obwohl — endlich verstehen",
 subs:[["a2","nebensatz"],["b1","nebensatz2"],["b1","temporalsatz"],["b1","konditional"],["b1","konsekutiv"],["c1","konzessiv"]]},
{id:"relativsaetze", name:"Relativsätze", en:"Relative clauses", icon:"↪", color:"#9333ea",
 desc:"Der Mann, der dort steht — Nomen mit einem ganzen Satz beschreiben.",
 yt:"Bl1Eg39hnf0", ytTitle:"Endlich Relativsätze verstehen",
 subs:[["b1","relativ"]]},
{id:"infinitivsaetze", name:"Infinitivsätze", en:"Infinitive clauses", icon:"↝", color:"#9333ea",
 desc:"zu + Infinitiv, um … zu, ohne … zu — kurze elegante Konstruktionen.",
 yt:"QQCBksqogHg", ytTitle:"Infinitiv mit zu — A2 bis B2",
 subs:[["b1","infinitiv"]]},
{id:"konnektoren", name:"Konnektoren", en:"Connectors", icon:"⟷", color:"#e07a08",
 desc:"deshalb, trotzdem, außerdem — Sätze verbinden und Gedanken ordnen.",
 yt:"z5XmNarv3jA", ytTitle:"Deutsch Konnektoren komplett erklärt",
 subs:[["a2","konnektoren"],["b1","zweiteilig"],["b2","konnektoren2"],["b2","konjunktionaladverb"],["c1","konnektorenc1"],["c1","kohaesion"]]},
{id:"interpunktion", name:"Interpunktion & Schreibung", en:"Punctuation & spelling", icon:"✎", color:"#b45309",
 desc:"Komma, Großschreibung und alle anderen Zeichen.",
 yt:"vXuyvv7t9hs", ytTitle:"Kommaregeln und Kommasetzung",
 subs:[["a1","grossschreibung"],["a2","komma"],["b1","kommab1"],["c1","interpunktionc1"]]},
{id:"stil", name:"Wortbildung & Stil", en:"Word formation & style", icon:"⚒", color:"#c2185b",
 desc:"Nominalstil, Komposita, Partizipien und die richtige Sprachebene.",
 yt:"nE-QIHBLWdg", ytTitle:"Nominalstil und Nominalisierung im Deutschen",
 subs:[["b2","nominal"],["c1","nominalc1"],["b2","komposita"],["b2","partizip"],["c1","partizipc1"],["c1","nominalphrase"],["b2","nomenverb"],["b2","modalpartikel"],["c1","wortbildungc1"],["c2","wortbildungc2"],["c2","stilebenen"],["c2","rhetorik"],["c2","textsorten"],["c2","varietaeten"],["c2","sprachwandel"],["c2","phonetik"]]},
{id:"wortschatz", name:"Wortschatz & Redemittel", en:"Vocabulary & phrases", icon:"✦", color:"#64748b",
 desc:"Kein Grammatikthema, aber unverzichtbar: Wörter, Wendungen und fertige Sätze.",
 yt:"", ytSearch:"Deutsch Redemittel Diskussion Meinung äußern",
 subs:[["a1","zahlen"],["a1","adverbien"],["a1","wortschatz"],["a1","redemittel"],["a2","haeufigeverben2"],["a2","wortschatz2"],["a2","redemittel2"],["b1","wortschatz3"],["b1","redemittel3"],["b2","haeufigeverben4"],["b2","wortschatz4"],["b2","redemittel4"],["c1","wortschatzc1"],["c1","redemittelc1"],["c2","idiomatik"],["c2","redemittelc2"],["b1","lassen"]]}
];
