/* FLOß – Verbdatenbank
   v=Infinitiv, en=Bedeutung, du/er=unregelmäßige Präsensformen, prt=Präteritumstamm,
   pp=Partizip II, aux=haben/sein, w=schwach(regelmäßig), sep=trennbare Vorsilbe, f=volle Formen */
window.VERBS = [
{v:"sein",en:"to be",aux:"ist",f:{pr:["bin","bist","ist","sind","seid","sind"],pt:["war","warst","war","waren","wart","waren"]},pp:"gewesen"},
{v:"haben",en:"to have",aux:"hat",f:{pr:["habe","hast","hat","haben","habt","haben"],pt:["hatte","hattest","hatte","hatten","hattet","hatten"]},pp:"gehabt"},
{v:"werden",en:"to become",aux:"ist",f:{pr:["werde","wirst","wird","werden","werdet","werden"],pt:["wurde","wurdest","wurde","wurden","wurdet","wurden"]},pp:"geworden"},
{v:"können",en:"can, to be able to",aux:"hat",f:{pr:["kann","kannst","kann","können","könnt","können"],pt:["konnte","konntest","konnte","konnten","konntet","konnten"]},pp:"gekonnt"},
{v:"müssen",en:"must, to have to",aux:"hat",f:{pr:["muss","musst","muss","müssen","müsst","müssen"],pt:["musste","musstest","musste","mussten","musstet","mussten"]},pp:"gemusst"},
{v:"wollen",en:"to want",aux:"hat",f:{pr:["will","willst","will","wollen","wollt","wollen"],pt:["wollte","wolltest","wollte","wollten","wolltet","wollten"]},pp:"gewollt"},
{v:"sollen",en:"should, to be supposed to",aux:"hat",f:{pr:["soll","sollst","soll","sollen","sollt","sollen"],pt:["sollte","solltest","sollte","sollten","solltet","sollten"]},pp:"gesollt"},
{v:"dürfen",en:"may, to be allowed to",aux:"hat",f:{pr:["darf","darfst","darf","dürfen","dürft","dürfen"],pt:["durfte","durftest","durfte","durften","durftet","durften"]},pp:"gedurft"},
{v:"mögen",en:"to like",aux:"hat",f:{pr:["mag","magst","mag","mögen","mögt","mögen"],pt:["mochte","mochtest","mochte","mochten","mochtet","mochten"]},pp:"gemocht"},
{v:"möchten",en:"would like",aux:"hat",f:{pr:["möchte","möchtest","möchte","möchten","möchtet","möchten"],pt:["wollte","wolltest","wollte","wollten","wolltet","wollten"]},pp:"gewollt",note:"Höflichkeitsform von mögen · polite form"},
{v:"wissen",en:"to know (a fact)",aux:"hat",f:{pr:["weiß","weißt","weiß","wissen","wisst","wissen"],pt:["wusste","wusstest","wusste","wussten","wusstet","wussten"]},pp:"gewusst"},

{v:"gehen",en:"to go",prt:"ging",pp:"gegangen",aux:"ist"},
{v:"kommen",en:"to come",prt:"kam",pp:"gekommen",aux:"ist"},
{v:"fahren",en:"to drive, to go",du:"fährst",er:"fährt",prt:"fuhr",pp:"gefahren",aux:"ist"},
{v:"laufen",en:"to run, to walk",du:"läufst",er:"läuft",prt:"lief",pp:"gelaufen",aux:"ist"},
{v:"fliegen",en:"to fly",prt:"flog",pp:"geflogen",aux:"ist"},
{v:"bleiben",en:"to stay",prt:"blieb",pp:"geblieben",aux:"ist"},
{v:"essen",en:"to eat",du:"isst",er:"isst",prt:"aß",pp:"gegessen",aux:"hat"},
{v:"trinken",en:"to drink",prt:"trank",pp:"getrunken",aux:"hat"},
{v:"sehen",en:"to see",du:"siehst",er:"sieht",prt:"sah",pp:"gesehen",aux:"hat"},
{v:"lesen",en:"to read",du:"liest",er:"liest",prt:"las",pp:"gelesen",aux:"hat"},
{v:"sprechen",en:"to speak",du:"sprichst",er:"spricht",prt:"sprach",pp:"gesprochen",aux:"hat"},
{v:"nehmen",en:"to take",du:"nimmst",er:"nimmt",prt:"nahm",pp:"genommen",aux:"hat"},
{v:"geben",en:"to give",du:"gibst",er:"gibt",prt:"gab",pp:"gegeben",aux:"hat"},
{v:"finden",en:"to find",prt:"fand",pp:"gefunden",aux:"hat"},
{v:"helfen",en:"to help (+ dative)",du:"hilfst",er:"hilft",prt:"half",pp:"geholfen",aux:"hat"},
{v:"schlafen",en:"to sleep",du:"schläfst",er:"schläft",prt:"schlief",pp:"geschlafen",aux:"hat"},
{v:"schreiben",en:"to write",prt:"schrieb",pp:"geschrieben",aux:"hat"},
{v:"stehen",en:"to stand",prt:"stand",pp:"gestanden",aux:"hat"},
{v:"liegen",en:"to lie, to be located",prt:"lag",pp:"gelegen",aux:"hat"},
{v:"sitzen",en:"to sit",prt:"saß",pp:"gesessen",aux:"hat"},
{v:"treffen",en:"to meet",du:"triffst",er:"trifft",prt:"traf",pp:"getroffen",aux:"hat"},
{v:"tragen",en:"to carry, to wear",du:"trägst",er:"trägt",prt:"trug",pp:"getragen",aux:"hat"},
{v:"halten",en:"to hold, to stop",du:"hältst",er:"hält",prt:"hielt",pp:"gehalten",aux:"hat"},
{v:"lassen",en:"to let, to have done",du:"lässt",er:"lässt",prt:"ließ",pp:"gelassen",aux:"hat"},
{v:"denken",en:"to think",prt:"dachte",pp:"gedacht",aux:"hat"},
{v:"bringen",en:"to bring",prt:"brachte",pp:"gebracht",aux:"hat"},
{v:"kennen",en:"to know (a person/thing)",prt:"kannte",pp:"gekannt",aux:"hat"},
{v:"nennen",en:"to name, to call",prt:"nannte",pp:"genannt",aux:"hat"},
{v:"rennen",en:"to run",prt:"rannte",pp:"gerannt",aux:"ist"},
{v:"verlieren",en:"to lose",prt:"verlor",pp:"verloren",aux:"hat"},
{v:"gewinnen",en:"to win",prt:"gewann",pp:"gewonnen",aux:"hat"},
{v:"beginnen",en:"to begin",prt:"begann",pp:"begonnen",aux:"hat"},
{v:"bitten",en:"to ask, to request",prt:"bat",pp:"gebeten",aux:"hat"},
{v:"bieten",en:"to offer",prt:"bot",pp:"geboten",aux:"hat"},
{v:"ziehen",en:"to pull, to move",prt:"zog",pp:"gezogen",aux:"hat"},
{v:"steigen",en:"to climb, to rise",prt:"stieg",pp:"gestiegen",aux:"ist"},
{v:"sterben",en:"to die",du:"stirbst",er:"stirbt",prt:"starb",pp:"gestorben",aux:"ist"},
{v:"wachsen",en:"to grow",du:"wächst",er:"wächst",prt:"wuchs",pp:"gewachsen",aux:"ist"},
{v:"waschen",en:"to wash",du:"wäschst",er:"wäscht",prt:"wusch",pp:"gewaschen",aux:"hat"},
{v:"fallen",en:"to fall",du:"fällst",er:"fällt",prt:"fiel",pp:"gefallen",aux:"ist"},
{v:"gefallen",en:"to please, to like (+ dative)",du:"gefällst",er:"gefällt",prt:"gefiel",pp:"gefallen",aux:"hat"},
{v:"vergessen",en:"to forget",du:"vergisst",er:"vergisst",prt:"vergaß",pp:"vergessen",aux:"hat"},
{v:"verstehen",en:"to understand",prt:"verstand",pp:"verstanden",aux:"hat"},
{v:"bekommen",en:"to receive, to get",prt:"bekam",pp:"bekommen",aux:"hat"},
{v:"empfehlen",en:"to recommend",du:"empfiehlst",er:"empfiehlt",prt:"empfahl",pp:"empfohlen",aux:"hat"},
{v:"entscheiden",en:"to decide",prt:"entschied",pp:"entschieden",aux:"hat"},
{v:"vergleichen",en:"to compare",prt:"verglich",pp:"verglichen",aux:"hat"},
{v:"verbinden",en:"to connect",prt:"verband",pp:"verbunden",aux:"hat"},
{v:"schließen",en:"to close",prt:"schloss",pp:"geschlossen",aux:"hat"},
{v:"beschließen",en:"to decide, to resolve",prt:"beschloss",pp:"beschlossen",aux:"hat"},
{v:"genießen",en:"to enjoy",prt:"genoss",pp:"genossen",aux:"hat"},
{v:"heißen",en:"to be called",prt:"hieß",pp:"geheißen",aux:"hat"},
{v:"scheinen",en:"to shine, to seem",prt:"schien",pp:"geschienen",aux:"hat"},
{v:"steigern",en:"to increase",prt:"steigerte",pp:"gesteigert",aux:"hat",w:1},
{v:"springen",en:"to jump",prt:"sprang",pp:"gesprungen",aux:"ist"},
{v:"singen",en:"to sing",prt:"sang",pp:"gesungen",aux:"hat"},
{v:"trinken ",en:"",skip:1},
{v:"schwimmen",en:"to swim",prt:"schwamm",pp:"geschwommen",aux:"ist"},
{v:"werfen",en:"to throw",du:"wirfst",er:"wirft",prt:"warf",pp:"geworfen",aux:"hat"},
{v:"treten",en:"to step, to kick",du:"trittst",er:"tritt",prt:"trat",pp:"getreten",aux:"ist"},
{v:"bitten ",en:"",skip:1},
{v:"raten",en:"to advise, to guess",du:"rätst",er:"rät",prt:"riet",pp:"geraten",aux:"hat"},
{v:"fangen",en:"to catch",du:"fängst",er:"fängt",prt:"fing",pp:"gefangen",aux:"hat"},
{v:"hängen",en:"to hang",prt:"hing",pp:"gehangen",aux:"hat"},
{v:"schneiden",en:"to cut",prt:"schnitt",pp:"geschnitten",aux:"hat"},
{v:"leiden",en:"to suffer",prt:"litt",pp:"gelitten",aux:"hat"},
{v:"streiten",en:"to argue",prt:"stritt",pp:"gestritten",aux:"hat"},
{v:"reiten",en:"to ride",prt:"ritt",pp:"geritten",aux:"ist"},
{v:"greifen",en:"to grab",prt:"griff",pp:"gegriffen",aux:"hat"},
{v:"pfeifen",en:"to whistle",prt:"pfiff",pp:"gepfiffen",aux:"hat"},
{v:"riechen",en:"to smell",prt:"roch",pp:"gerochen",aux:"hat"},
{v:"schießen",en:"to shoot",prt:"schoss",pp:"geschossen",aux:"hat"},
{v:"gießen",en:"to pour, to water",prt:"goss",pp:"gegossen",aux:"hat"},
{v:"fließen",en:"to flow",prt:"floss",pp:"geflossen",aux:"ist"},
{v:"beweisen",en:"to prove",prt:"bewies",pp:"bewiesen",aux:"hat"},
{v:"steigen ",en:"",skip:1},
{v:"weisen",en:"to point",prt:"wies",pp:"gewiesen",aux:"hat"},
{v:"binden",en:"to tie",prt:"band",pp:"gebunden",aux:"hat"},
{v:"trinken  ",en:"",skip:1},
{v:"gelingen",en:"to succeed",prt:"gelang",pp:"gelungen",aux:"ist"},
{v:"zwingen",en:"to force",prt:"zwang",pp:"gezwungen",aux:"hat"},
{v:"sprießen",en:"",skip:1},
{v:"betreten",en:"to enter",du:"betrittst",er:"betritt",prt:"betrat",pp:"betreten",aux:"hat"},
{v:"erfinden",en:"to invent",prt:"erfand",pp:"erfunden",aux:"hat"},
{v:"geschehen",en:"to happen",er:"geschieht",prt:"geschah",pp:"geschehen",aux:"ist"},
{v:"gelten",en:"to be valid",du:"giltst",er:"gilt",prt:"galt",pp:"gegolten",aux:"hat"},
{v:"schaffen",en:"to manage, to create",prt:"schuf",pp:"geschaffen",aux:"hat"},

{v:"machen",en:"to do, to make",w:1,aux:"hat"},
{v:"sagen",en:"to say",w:1,aux:"hat"},
{v:"fragen",en:"to ask",w:1,aux:"hat"},
{v:"lernen",en:"to learn",w:1,aux:"hat"},
{v:"wohnen",en:"to live, to reside",w:1,aux:"hat"},
{v:"kaufen",en:"to buy",w:1,aux:"hat"},
{v:"spielen",en:"to play",w:1,aux:"hat"},
{v:"arbeiten",en:"to work",w:1,aux:"hat"},
{v:"lieben",en:"to love",w:1,aux:"hat"},
{v:"leben",en:"to live",w:1,aux:"hat"},
{v:"lachen",en:"to laugh",w:1,aux:"hat"},
{v:"weinen",en:"to cry",w:1,aux:"hat"},
{v:"kochen",en:"to cook",w:1,aux:"hat"},
{v:"suchen",en:"to look for",w:1,aux:"hat"},
{v:"brauchen",en:"to need",w:1,aux:"hat"},
{v:"hören",en:"to hear, to listen",w:1,aux:"hat"},
{v:"holen",en:"to fetch",w:1,aux:"hat"},
{v:"zeigen",en:"to show",w:1,aux:"hat"},
{v:"legen",en:"to lay, to put",w:1,aux:"hat"},
{v:"stellen",en:"to place, to put",w:1,aux:"hat"},
{v:"setzen",en:"to set, to seat",w:1,aux:"hat"},
{v:"öffnen",en:"to open",w:1,aux:"hat"},
{v:"warten",en:"to wait (auf + acc.)",w:1,aux:"hat"},
{v:"antworten",en:"to answer (+ dative)",w:1,aux:"hat"},
{v:"danken",en:"to thank (+ dative)",w:1,aux:"hat"},
{v:"gehören",en:"to belong (+ dative)",w:1,aux:"hat"},
{v:"schmecken",en:"to taste (+ dative)",w:1,aux:"hat"},
{v:"passen",en:"to fit (+ dative)",w:1,aux:"hat"},
{v:"glauben",en:"to believe",w:1,aux:"hat"},
{v:"lernen ",en:"",skip:1},
{v:"üben",en:"to practise",w:1,aux:"hat"},
{v:"reisen",en:"to travel",w:1,aux:"ist"},
{v:"tanzen",en:"to dance",w:1,aux:"hat"},
{v:"rauchen",en:"to smoke",w:1,aux:"hat"},
{v:"zahlen",en:"to pay",w:1,aux:"hat"},
{v:"bezahlen",en:"to pay for",w:1,aux:"hat"},
{v:"bestellen",en:"to order",w:1,aux:"hat"},
{v:"besuchen",en:"to visit",w:1,aux:"hat"},
{v:"erzählen",en:"to tell",w:1,aux:"hat"},
{v:"erklären",en:"to explain",w:1,aux:"hat"},
{v:"verkaufen",en:"to sell",w:1,aux:"hat"},
{v:"versuchen",en:"to try",w:1,aux:"hat"},
{v:"verdienen",en:"to earn",w:1,aux:"hat"},
{v:"benutzen",en:"to use",w:1,aux:"hat"},
{v:"beantworten",en:"to answer (+ acc.)",w:1,aux:"hat"},
{v:"bedeuten",en:"to mean",w:1,aux:"hat"},
{v:"betonen",en:"to emphasize",w:1,aux:"hat"},
{v:"behaupten",en:"to claim",w:1,aux:"hat"},
{v:"beobachten",en:"to observe",w:1,aux:"hat"},
{v:"begründen",en:"to justify",w:1,aux:"hat"},
{v:"berücksichtigen",en:"to take into account",w:1,aux:"hat"},
{v:"entwickeln",en:"to develop",w:1,aux:"hat"},
{v:"ermöglichen",en:"to enable",w:1,aux:"hat"},
{v:"verhindern",en:"to prevent",w:1,aux:"hat"},
{v:"fördern",en:"to promote, to support",w:1,aux:"hat"},
{v:"telefonieren",en:"to phone",w:1,aux:"hat",noge:1},
{v:"studieren",en:"to study",w:1,aux:"hat",noge:1},
{v:"passieren",en:"to happen",w:1,aux:"ist",noge:1},
{v:"reparieren",en:"to repair",w:1,aux:"hat",noge:1},
{v:"funktionieren",en:"to work, to function",w:1,aux:"hat",noge:1},
{v:"diskutieren",en:"to discuss",w:1,aux:"hat",noge:1},
{v:"informieren",en:"to inform",w:1,aux:"hat",noge:1},
{v:"organisieren",en:"to organize",w:1,aux:"hat",noge:1},
{v:"akzeptieren",en:"to accept",w:1,aux:"hat",noge:1},
{v:"kritisieren",en:"to criticize",w:1,aux:"hat",noge:1},

{v:"einkaufen",en:"to shop",w:1,aux:"hat",sep:"ein"},
{v:"einladen",en:"to invite",du:"lädst",er:"lädt",prt:"lud",pp:"eingeladen",aux:"hat",sep:"ein"},
{v:"einschlafen",en:"to fall asleep",du:"schläfst",er:"schläft",prt:"schlief",pp:"eingeschlafen",aux:"ist",sep:"ein"},
{v:"einsteigen",en:"to get in/on",prt:"stieg",pp:"eingestiegen",aux:"ist",sep:"ein"},
{v:"aufstehen",en:"to get up",prt:"stand",pp:"aufgestanden",aux:"ist",sep:"auf"},
{v:"aufhören",en:"to stop",w:1,aux:"hat",sep:"auf"},
{v:"aufmachen",en:"to open",w:1,aux:"hat",sep:"auf"},
{v:"aufräumen",en:"to tidy up",w:1,aux:"hat",sep:"auf"},
{v:"anrufen",en:"to call, to phone",prt:"rief",pp:"angerufen",aux:"hat",sep:"an"},
{v:"anfangen",en:"to begin",du:"fängst",er:"fängt",prt:"fing",pp:"angefangen",aux:"hat",sep:"an"},
{v:"ankommen",en:"to arrive",prt:"kam",pp:"angekommen",aux:"ist",sep:"an"},
{v:"anziehen",en:"to put on (clothes)",prt:"zog",pp:"angezogen",aux:"hat",sep:"an"},
{v:"ausgehen",en:"to go out",prt:"ging",pp:"ausgegangen",aux:"ist",sep:"aus"},
{v:"ausfüllen",en:"to fill in",w:1,aux:"hat",sep:"aus"},
{v:"aussehen",en:"to look, to appear",du:"siehst",er:"sieht",prt:"sah",pp:"ausgesehen",aux:"hat",sep:"aus"},
{v:"mitkommen",en:"to come along",prt:"kam",pp:"mitgekommen",aux:"ist",sep:"mit"},
{v:"mitbringen",en:"to bring along",prt:"brachte",pp:"mitgebracht",aux:"hat",sep:"mit"},
{v:"mitnehmen",en:"to take along",du:"nimmst",er:"nimmt",prt:"nahm",pp:"mitgenommen",aux:"hat",sep:"mit"},
{v:"zuhören",en:"to listen (+ dative)",w:1,aux:"hat",sep:"zu"},
{v:"zumachen",en:"to close",w:1,aux:"hat",sep:"zu"},
{v:"umziehen",en:"to move house",prt:"zog",pp:"umgezogen",aux:"ist",sep:"um"},
{v:"umsteigen",en:"to change (trains)",prt:"stieg",pp:"umgestiegen",aux:"ist",sep:"um"},
{v:"vorstellen",en:"to introduce, to imagine",w:1,aux:"hat",sep:"vor"},
{v:"vorbereiten",en:"to prepare",w:1,aux:"hat",sep:"vor"},
{v:"weggehen",en:"to go away",prt:"ging",pp:"weggegangen",aux:"ist",sep:"weg"},
{v:"zurückkommen",en:"to come back",prt:"kam",pp:"zurückgekommen",aux:"ist",sep:"zurück"},
{v:"teilnehmen",en:"to participate (an + dat.)",du:"nimmst",er:"nimmt",prt:"nahm",pp:"teilgenommen",aux:"hat",sep:"teil"},
{v:"stattfinden",en:"to take place",prt:"fand",pp:"stattgefunden",aux:"hat",sep:"statt"},
{v:"abholen",en:"to pick up",w:1,aux:"hat",sep:"ab"},
{v:"abfahren",en:"to depart",du:"fährst",er:"fährt",prt:"fuhr",pp:"abgefahren",aux:"ist",sep:"ab"},
{v:"nachdenken",en:"to think about (über + acc.)",prt:"dachte",pp:"nachgedacht",aux:"hat",sep:"nach"},
{v:"herunterladen",en:"to download",du:"lädst",er:"lädt",prt:"lud",pp:"heruntergeladen",aux:"hat",sep:"herunter"},

{v:"sich freuen",en:"to be happy (über/auf)",w:1,aux:"hat",refl:1},
{v:"sich beeilen",en:"to hurry",w:1,aux:"hat",refl:1},
{v:"sich interessieren",en:"to be interested (für + acc.)",w:1,aux:"hat",refl:1,noge:1},
{v:"sich erinnern",en:"to remember (an + acc.)",w:1,aux:"hat",refl:1},
{v:"sich entschuldigen",en:"to apologize",w:1,aux:"hat",refl:1},
{v:"sich bewerben",en:"to apply (um + acc.)",du:"bewirbst",er:"bewirbt",prt:"bewarb",pp:"beworben",aux:"hat",refl:1},
{v:"sich unterhalten",en:"to chat (mit + dat.)",du:"unterhältst",er:"unterhält",prt:"unterhielt",pp:"unterhalten",aux:"hat",refl:1},
{v:"sich befinden",en:"to be located",prt:"befand",pp:"befunden",aux:"hat",refl:1}
].filter(x=>!x.skip);
